name: Eslint tests

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run eslint
        run: yarn lint
